name: "Rook Webook"
branding:
  icon: 'anchor'
  color: 'purple'
description: "Send a signed post body to an endpoint"
inputs:
  endpoint:
    description: 'endpoint listening for signed webhooks'
    required: true
  secret:
    description: 'shared secret used to sign the body'
    required: true
  body:
    description: 'request body.  A rook server will export this as $ROOK_INPUT'
    required: true
runs:
  using: 'docker'
  image: 'docker://numberoverzero/rook-action:v2'
