[package]
name = "rook-action"
version = "0.1.0"
edition = "2021"

[dependencies]
hmac = { version = "0.11" }
sha2 = { version = "0.9" }
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"], default-features = false }