[package]
name = "rook-action"
version = "0.1.0"
edition = "2021"

[dependencies]
hmac = { version = "0.12" }
sha2 = { version = "0.10" }
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"], default-features = false }